comment:
  layout: "reach,diff,flags,tree"
  behavior: new
coverage:
  status:
    project:
      default:
        target: 100%
        informational: true
    patch:
      default:
        target: 100%